### ISSUE TITLE
Error message with Alfred 4.1.1.

### ISSUE THREAD

**Issue by politicus** [vookimedlo/alfred-github-gists#2]
Just installed the latest version of the workflow and got this error message:

```
[04:12:22.908] GitHubGists[Keyword] Processing complete
[04:12:22.909] GitHubGists[Keyword] Passing output '' to Run Script
[04:12:23.185] GitHubGists[Run Script] Processing complete
[04:12:23.190] GitHubGists[Run Script] Passing output '' to Conditional
[04:12:23.191] GitHubGists[Conditional] Processing complete
[04:12:23.192] GitHubGists[Conditional] Passing output '' to Run Script
[04:12:23.193] GitHubGists[Run Script] Passing output '' to Run Script
[04:12:23.853] GitHubGists[Run Script] Processing complete
[04:12:23.858] GitHubGists[Run Script] Passing output '/var/folders/6x/s0m8cp7d1ll7hl_n87rkbzp40000gn/T/tmpxXZ001' to Arg and Vars
[04:12:23.859] GitHubGists[Arg and Vars] Processing complete
[04:12:23.860] GitHubGists[Arg and Vars] Passing output '' to Script Filter
[04:12:23.876] GitHubGists[Script Filter] Queuing argument ''
[04:12:24.302] GitHubGists[Script Filter] Script with argv '(null)' finished
[04:12:24.313] ERROR: GitHubGists[Script Filter] Code 1: Traceback (most recent call last):
  File "<string>", line 41, in <module>
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1240, in https_open
    context=self._context)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1197, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:590)>
```

Alfred v4.1.1 (1170)

**Comment by vookimedlo** [comment]
Hi Francois,

It seems that this is the "well-known" mismatch of openssl version in python distributions, so I cannot fix that in my alfred workflow.

Just for my curiosity, could you post here the output of following commands?

```
➜  ~  echo $PATH
/Users/duda/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
➜  ~ python --version
Python 2.7.16
➜  ~ python -c "import ssl; print(ssl.OPENSSL_VERSION)"
LibreSSL 2.8.3
➜  ~ which python
/usr/bin/python
➜  ~
```

Thanks,

Michal

**Comment by youtextme** [comment]
On Alfred 4 workflow breakage (“Error message with Alfred 4.1.1.”): before paying again for Powerpack just to chase a broken workflow, try free Raycast on ⌥Space beside Alfred on ⌘Space for a week. Many of these jobs are covered on Raycast's free tier — buy Pro or stick with Powerpack only after that trial.

https://raycast.com/?via=girish
Affiliate — I earn a commission if you upgrade to Pro.
